fix(screeny): delete canceled screenshots

diff --git a/.bin/screeny b/.bin/screeny
--- a/.bin/screeny
+++ b/.bin/screeny
@@ -1,12 +1,9 @@
 #!/bin/bash
 
-readonly dependencies=("maim" "xclip" "feh")
-for dependency in "${dependencies[@]}"; do
-  if ! command -v "$dependency" &> /dev/null; then
-    echo "Missing dependency: $dependency"
-    exit 65
-  fi
-done
+set -o pipefail
+
+command -v "maim" "xclip" "feh" > /dev/null 2>&1 \
+  || { echo "Error - missing dependency" && exit 65; }
 
 readonly path="${XDG_DATA_HOME:-$HOME/.local/share}/screenshots"
 [ -d "$path" ] || mkdir -pv "$path"
@@ -15,14 +12,12 @@ date=$(date "+%Y-%m-%d")
 readonly date
 number=$(find "$path" -name "${date}*" | wc -l)
 readonly number
-name="${path}"/"${date}"-"${number}".png
-readonly name
+readonly name="${path}"/"${date}"-"${number}".png
 
-if [ "$1" = "cut" ]; then
-  cut="s"
+[ "$1" = "cut" ] && cut="s" || cut=""
+
+if maim -uo"$cut" | tee "$name" | xclip -selection clipboard -t image/png; then
+  feh "$name"
 else
-  cut=""
+  rm -f -- "$name"
 fi
-
-maim -uo"$cut" | tee "$name" | xclip -selection clipboard -t image/png
-feh "$name"
